### ISSUE TITLE
Geoserver on clio-infra

### ISSUE THREAD

**Issue by morkor** [CLARIAH/wp4-requirements#124]
From Bas: I just got a mail from Slava asking what has happened to the geoserver from clio-infra. 
If it is no longer being used, DANS might be interested in hosting it.
My response: for the moment it will be still in use (we will keep the old website accessible for a few months as some people might still need it). After that period I do not know if it will become redundant, because the plan is to have maps for the new version of the website as well.

So do we need it beyond this short period, or the maps on the new website will have a different structure/backbone?

**Comment by 4tikhonov** [comment]
Well, basically I was asking about geo server developed by webmapper and delivering polygons, it has nothing to do with javascript application working on the old Clio Infra website that shows dynamic maps.
