### ISSUE TITLE
druid -> cattle binary file download

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/wp4-requirements#149]

**Comment by LaurensRietveld** [comment]
To list the files you'd like to upload:
`https://api.druid.datalegend.net/datasets/<user>/<dsname>/files`

To download a file, use the same url and append `/<filename>`

**Comment by albertmeronyo** [comment]
Cattle CSV->RDF conversions now work by downloading binary files from druid repos. Can be triggered via URLs like cattlehost/druid/<username>/<dataset>
Cattle will:
- Get a list of files
- Look for .csv files, and for those see if they have a matching pair .csv-metadata.json
- For all pairs, will run the conversion and (temporarily) return .nq.gz files to the browser

The latter will change into upload once tokens are ready.
