### ISSUE TITLE
Cattle registering webhook

### ISSUE THREAD

**Issue by LaurensRietveld** [CLARIAH/wp4-requirements#152]
To register a webhook:

- Get organizations the cattle user is a member of: `curl https://api.druid.datalegend.net/accounts/cattle/orgs -H "Authorization: Bearer <TOKEN>"
- For each organization, _optionally_ check the last modified date (if it's larger than a few hours ago, then there is no need to register new web hooks)
- Get the datasets of an org: `curl https://api.druid.datalegend.net/datasets/<org> -H "Authorization: <TOKEN>"`
- Get tokens of a dataset: TODO
- Register a token for a dataset TODO

**Comment by LaurensRietveld** [comment]
(I'll update the TODOs when the new druid version is released)

**Comment by ekulno** [comment]
# Webhooks

Webhook functionality has been added in the latest release, allowing you to send a signal to wherever you like upon certain kinds of events related to your dataset. 

## Creating a WebHook

To create a webhook through the API, you can send a POST request with a configuration for your new hook. 

The required fields are the following:

	active:<boolean>,
	onEvents:{
		fileUpload:<boolean>,
		graphImport:<boolean>,
		linkedDataUpload:<boolean>
	}
	payloadFormat:<'JSON'|'formEncoded'>,
	url:<a http(s)-url>

You will also need to include an API token in the header. Include it as the value of 'jwt' in the cookie. 

An example curl command: `curl -d '{"active":true, "onEvents":{"fileUpload":true, "graphImport":false,"linkedDataUpload":true},"payloadFormat":"JSON","url":"http://example.com/"}' -H "Content-Type: application/json" -H "Cookie: jwt=myVerySecretToken" -X POST https://api.druid.datalegend.net/datasets/myAccountName/myDatasetName/hooks/`

The response should be a JSON object containing the configuration you just submitted, as well as its unique ID. 

With this configuration, a http request will be sent to the target url (http://example.com) with information relevant to the event whenever one of the enabled events occur. 

## List Webhook Trigger Records

After having created a webhook, you can upload a file, import a graph, or finish a job (depending on your webhook configuration) to trigger the new hook. Now, there will be a record of the webhook triggering event in the database, which you can request through the API: `curl -d  -H "Cookie: jwt=myVerySecretToken" -X GET https://api.druid.datalegend.net/datasets/myAccountName/myDatasetName/hookrecords/<hookId>?offset=0&limit=10`, where <hookId> is the unique ID which was returned when you submitted the hook. 

## Editing a Webhook

To edit your configuration, specify the unique hook id and the fields you want to change in a PATCH request: `curl -d '{"id":"<hookId>","active":false}' -H "Content-Type: application/json" -H "Cookie: jwt=myVerySecretToken" -X PATCH https://api.druid.datalegend.net/datasets/myAccountName/myDatasetName/hooks/<hookId>`. This will change only the value of the `active` field. 

## Deleting a Webhook

`curl -H "Cookie: jwt=myVerySecretToken" -X DELETE https://api.druid.datalegend.net/datasets/myAccountName/myDatasetName/hooks/<hookId>`. 

## List all Webhooks of a Dataset

`curl -H "Cookie: jwt=myVerySecretToken" -X GET https://api.druid.datalegend.net/datasets/myAccountName/myDatasetName/hooks`

## The Events

The supported events are: 

 - `graphImport`: Whenever a graph is imported to the dataset
 - `linkedDataUpload`: Whenever a Job has finished, and the dataset is populated with browsable triples
 - `fileUpload`: Whenever a file has been uploaded through the /myDatasetName/files route

Drop by with any questions you might have :)

**Comment by LaurensRietveld** [comment]
This is done now
