### ISSUE TITLE
Basic statistics summary for dataset

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/wp4-requirements#20]
Provide a summary of the basic statistics for a dataset.

The idea is to have something similar to the R 'summary' function.

Almost done. Will create a separate issue for integration in CSVW pipeline.

**Comment by RinkeHoekstra** [comment]
- How many variables are mapped onto others/reused by others.
- Who is the author (& other provenance)
- What is the source of the dataset
- Number of observations

**Comment by RinkeHoekstra** [comment]
Works for all statistics that SPARQL supports (so, no stdev).

Can be used in grlc queries...

http://grlc.io/api/CLARIAH/wp4-queries/api-docs

We will precompute these and then store them as 'cached'. Add a refresh button.

Question: 
- Where should this reside?
- Can we extend DataCube with this minimal statistics overview?

**Comment by albertmeronyo** [comment]
We use this issue to keep track of #19

**Comment by albertmeronyo** [comment]
- Idea is to do R summary() function on any variable of the hub
- Used original SPARQL query in inspector/overview
- Now query in grlc, uses stats functions available in SPARQL (see http://grlc.io/api/CLARIAH/wp4-queries/dimensions)
- Pros: on the fly, standards compatible
- Cons: slow, not extendable (we want materialization right?)

Action: materialize this in pandas at dataset ingestion time
Action: use CSVW to create a 'metadata' dataset summarizing stats of all datasets in the hub

Deferring this to next milestone

**Comment by RinkeHoekstra** [comment]
Albert has implemented this using Pandas. Jupyter notebook shows how it works for an example dataset. 

* Will be integrated with the conversion pipeline (and is designed to fit easily)
* Will use C-LOD statistics properties from LODLaundromat for capturing/storing the computed statistics.

**Comment by albertmeronyo** [comment]
For the record: the Jupyter notebook containing the CSVWStats code is at https://github.com/albertmeronyo/notebooks/blob/master/tests/CSVWStats.ipynb
