### ISSUE TITLE
Uniformly make sure all code uses the same base namespace

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/wp4-requirements#22]
We've been switching between `http://data.socialhistory.org/ns/resource/...` and `http://data.socialhistory.org/resource/...` (respectively `vocab`). 

The final decision is that it should be _without_ the `ns` infix. 

This decision should be propagated to all code.

**Comment by RinkeHoekstra** [comment]
Most if not all codebase has been fixed for this issue. There is a lot of legacy data around though...

**Comment by rlzijdeman** [comment]
We'll take care of that with spring clean. Closing this issue now.
