### ISSUE TITLE
"Online-only" version of QBer

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/wp4-requirements#24]
This should replace the need for local installation of QBer (and consequently related issues with versions of files).

**Comment by albertmeronyo** [comment]
+1 for this. Was very much needed in last week's tutorial in Loughborough.

**Comment by RinkeHoekstra** [comment]
In principle ready to ship, but need a migration path for existing installs.

**Comment by RinkeHoekstra** [comment]
## Milestone meeting

Goal for december 31st is: online version of QBer that works with the new Server.

Current status:
- There is a version that can run on the server
- Upload from dropbox is the only current way.
- Puts the data in a directory in the datalegend-test repository
- Cache is on server as well (in gitlab)
- Pressing publish will generate RDF, store it in Gitlab, and post to the triple store

Issues:
- Current work needs to be migrated (this can be done by hand) ... but nobody has.
- "academic"
- Uploaded data does not appear in inspector.
- Not yet rolled out on server... needed to close the issue.
