### ISSUE TITLE
CSVW & QBer datastructure merged

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/wp4-requirements#29]

**Comment by RinkeHoekstra** [comment]
I looked at this in some more detail and concluded that the CSVW format is not suitable to be used as internal data-format for QBer. The reasons are:

* CSVW uses dictionary arrays with 'keys' hidden in the dictionaries. This makes lookups too inefficient for use in a UI
* CSVW uses virtual column definitions to add additional triples (e.g. the type of a property that relates the row in a CSV file to a value). This is yet another dictionary-inside-an-array that has no link with the column being augmented. Linking the actual column with the virtual column(s) would require bookkeeping.
* CSVW does not provide a way to conveniently map values to each other. This means that transformations from e.g. 'f' to 'sdmx-code:sex-F' would have to be done inside a Jinja2 if-then-else statement inside a valueUrl... this is problematic for two reasons: 1) the Jinja2 solution is **already** an extension of CSVW and 2) rolling back these changes is really cumbersome. 
* CSVW does not provide an elegant way to include the original data as JSON. The csv2json spec of the W3C converts to a row-based representation which is again very inefficient for the way we need to traverse the data (columns are much faster).


Solution: generate CSVW spec directly from QBer cache specification on publication. Need to think on whether this solves the provenance issue (we'd like to have an explicit representation of how a dataset was converted from CSV to a linked RDF representation)

**Comment by RinkeHoekstra** [comment]
Closed
