### ISSUE TITLE
Data API at data.datalegend.net

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/wp4-requirements#32]
A grlc-enabled API granting access to data on the hub will be available at api.datalegend.net
This API ingests its functionality by using the SPARQL queries currently at https://github.com/CLARIAH/wp4-queries
grlc will be migrated in the server from its current manual installation to a docker instance made available at hub.docker.com as per CLARIAH/grlc#28
grlc will rely on external reverse proxing caching to solve current cache related bugs, e.g. CLARIAH/grlc#26

**Comment by RinkeHoekstra** [comment]
What about the non-SPARQL API that we now have in place at http://api.clariah-sdh.eculture.labs.vu.nl and its successor (partly what Laurens is developing). 

-Rinke

**Comment by albertmeronyo** [comment]
Good question. What we have now at http://api.clariah-sdh.eculture.labs.vu.nl/ seems to me the hub backend API, i.e. what's needed by QBer+converters to add/remove/change datasets.
This would be a public data-API to provide the cleaned data that are already available on the hub to final users/applications (i.e. to save them from accessing the hub by typing SPARQL)

**Comment by albertmeronyo** [comment]
While the question on having an alias at http://data.datalegend.net pointing at http://grlc.io/api/CLARIAH/wp4-queries remains, the rest of the issues (modular cache via reverse proxy, and docker image at http://hub.docker.com) have been solved, thus I'm closing the requirement.
