### ISSUE TITLE
MESO Datasets

### ISSUE THREAD

**Issue by AshkanA** [CLARIAH/wp4-requirements#36]
identify, study and select MESO data for the hub

**Comment by RinkeHoekstra** [comment]
We can document the results of this selection & consequent progress in https://docs.google.com/spreadsheets/d/1qrBDlZxr7lL3tskbUGvvap2grWRvCsgbuoqTKPDp_xI/edit?usp=sharing.

(there already is one meso dataset listed)

**Comment by AshkanA** [comment]
Thanks I'm aware of it, and also saw the Bagdad to London dataset. Currently i'm collecting everything which may fall under meso-data. After inspection and study of the contents I will select some (meso datasets) and discuss this with Auke and Richard..once agreed upon we can move the selected ones to this list.

for now, to avoid cluttering the current list, the first selection is reported here: https://docs.google.com/spreadsheets/d/1SwxfuW_-HZ1o5LS17xlKPmzHD-ZLsfQUiSLX6J8SaqA/edit#gid=0

**Comment by rlzijdeman** [comment]
At the moment we'll need to stick to this inventory. We can choose datasets from this list, later on, when we'll focus again on transposing datasets.
