### ISSUE TITLE
Review queries and datasets currently in GitLab

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/wp4-requirements#38]
Together with @RinkeHoekstra

**Comment by rijpma** [comment]
There are recurrent problems in the NAPP to HISCO queries. 

The former has no leading zeroes while the latter does; same goes for `/ns` in the namespaces. Tried to solve this the ugly way with `BIND(STRAFTER(...` and `BIND(CONCAT(...` but this slows the queries down so much they don't execute anymore. Best solved in the data?

**Comment by rijpma** [comment]
Work needs to be done on the datasets to make the queries work:
1. The Clio-Infra country codes need to lose their decimal zeroes.
2. The Clio-Infra country codes, insofar possible, need to refer to the ISO standard.
3. Fully updated NAPP RDF with correct OCCHISCO and references to Clio-Infra datasets.
4. Latest version of HISCO needs to be on the hub.

**Comment by rlzijdeman** [comment]
Most queries have been fixed, but data day has changed various schemes again. Resolving as 'won't fix' and making sure proper data only will be put on Druid.
