### ISSUE TITLE
plugin for communication between gitlab and dataverse

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/wp4-requirements#43]
Hi @RinkeHoekstra @albertmeronyo @LaurensRietveld ,

Perhaps this plugin would allow for communication between gitlab and the Dataverse Network, used by most Dutch institutions: https://git.it.vt.edu/chased89/ojsdev/tree/0c5d9dea094913a46fe55077ef9a075a9b7176b8/plugins/generic/dataverse

Could you please answer the following questions:
- can we copy files from dataverse to gitlab? (are current workflow uses gitlab, rather than DV)
- would it allow us add our derived rdf and converter inside a specific dataverse?

Best,

Richard

**Comment by RinkeHoekstra** [comment]
Hi Richard,

This plugin does not interact between Gitlab & Dataverse, but rather between the OKFN Open Journal System and Dataverse… so I’m afraid it is not of much use to us.

At the moment QBer already pulls from Dataverse and publishes to datalegend & GitLab… it does not yet publish back to Dataverse, as it requires us to deal with authentication & authorization.

-Rinke

**Comment by rlzijdeman** [comment]
Thanks for the quick response. I somehow assumed gitlab and OKFN could communicate.
