### ISSUE TITLE
hisco: replace hisco_45 descriptions with urls from historyofwork.iisg.nl

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/wp4-requirements#51]
NB: we're not allowed to showcase the descriptions from hisco_45

**Comment by RinkeHoekstra** [comment]
Do we have those links?

**Comment by rlzijdeman** [comment]
Hi, yes, they are on the historyofwork.iisg.nl<http://historyofwork.iisg.nl> website: http://historyofwork.iisg.nl/major.php this allows you to traverse through the major minor unit groups and 5-digit categories.

You mentioned this as a solution and is incorporated in V3 of the HISCO graph.

Ps: thanks for the response on this and other issues



On 10 Dec 2016, at 09:49, Rinke Hoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we have those links?

-

**Comment by rlzijdeman** [comment]
Urls added by @RinkeHoekstra . Thank you :)
