### ISSUE TITLE
Deployed console on VU server

### ISSUE THREAD

**Issue by LaurensRietveld** [CLARIAH/wp4-requirements#55]
To get started with API keys in tools such as QBer and Grlc, I deployed an instance of the console on a VU server.
Its accessible at clariah.lod.labs.vu.nl

ps. Now the KNAW server is up and running (#54), we should be able to easily deploy the console there as well

**Comment by RinkeHoekstra** [comment]
<http://clariah.lod.labs.vu.nl>
