### ISSUE TITLE
Convert empty values into RDF

### ISSUE THREAD

**Issue by RubenSchalk** [CLARIAH/wp4-requirements#67]
Different variables (PERSNRMX and PERSNRVX) in the BEVSTATP table (and possibly other tables) contain empty values that have meaning. The converter skips these empty cells at the moment but it would be good to find a way to keep them.

**Comment by rlzijdeman** [comment]
This issue is on the border of data cleaning. @RinkeHoekstra  could you please check whether it is possible to add something in the converter to deal with this sort of issue? (NB: just check, not code) :P

**Comment by RinkeHoekstra** [comment]
See https://github.com/CLARIAH/wp4-converters/commit/bc6c82e65f3a884664d74efd49bb8f2fdad1da2a
