### ISSUE TITLE
Null coding doesn't work for date variables

### ISSUE THREAD

**Issue by RubenSchalk** [CLARIAH/wp4-requirements#68]
Assigning null values to negative date values (gDay; gMonth; gYear) does not seem to work. Some have values of -2, -4 etc. but the converter does not change them into null values in the BEVSTATP table.

**Comment by rijpma** [comment]
I'm experiencing the same thing (for other datatypes than date), but I think this should be an issue over at https://github.com/CLARIAH/wp4-converters . Alternatively @RinkeHoekstra should be assignee because I don't think the two of us be able to fix this in the converter.
