### ISSUE TITLE
Ability to handle different input data formats

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/wp4-requirements#7]
- With micro, meso and macro-data
- In CSC, SAV (SPSS metadata), ODS, XLS

**Comment by RinkeHoekstra** [comment]
There is a lot of code already in place to support this, including the normalization of ClioInfra-style data.

**Comment by rlzijdeman** [comment]
won't fix. please just save your file as .csv in Excel, SPSS, Stata, R, whatever and then upload to QBer.
