### ISSUE TITLE
Datasets corresponding to historical borders

### ISSUE THREAD

**Issue by morkor** [CLARIAH/wp4-requirements#70]
Add a list of data that are available for historical borders. This would be the page to display when clicking on the "For available datasets with historical boundaries click here". This is on the dataset level within pages, that means it is shown in the warning box right before the dataset menu.

**Comment by morkor** [comment]
depending on the size of the dataset of historical territories, I think I will minimize this to an instant download of an xlsx file with the respective data.

**Comment by morkor** [comment]
to be coded just as a subset of the entire list of data

**Comment by rlzijdeman** [comment]
What do you mean?

**Comment by morkor** [comment]
it is just a note on how I will implement it in R.
