### ISSUE TITLE
well being index

### ISSUE THREAD

**Issue by morkor** [CLARIAH/wp4-requirements#77]
Make more of a story out of the well being index of Auke in Clio Infra.

**Comment by morkor** [comment]
add the data for download

**Comment by morkor** [comment]
this is a very demanding case as it introduces about 60 new territories with each having data points.

**Comment by rijpma** [comment]
Note that all the observations for these territories are highly uncertain because the rest of the clio-data will be very sparse for them. They'll by and large be 100% imputed.

In other words, not an awful lot is lot if they don't have their own page etc.

**Comment by morkor** [comment]
thanks, then would it be a problem to remove those cases from the website and only keep those entries for which we have (other) data already?

**Comment by morkor** [comment]
I could add the datafile as it is on dataverse and then upload a new version (smaller and only having relevant countries for the website) that will be used for building the website. Would that be OK?

**Comment by rijpma** [comment]
Would work for me, though I'd be OK with having only the version with relevant countries online as well.

**Comment by morkor** [comment]
OK in dataverse this is done : https://datasets.socialhistory.org/dataset.xhtml?persistentId=hdl%3A10622%2FQIPFQF, now I am updating the scripts for incorporating this on the website too.

**Comment by morkor** [comment]
done and will be uploaded to github

**Comment by morkor** [comment]
change the citation to:
Rijpma, Auke. 2014. “A Composite View of Well-Being since 1820.” In How Was Life? Global Well-Being since 1820, edited by Jan Luiten Van Zanden, Joerg Baten, Marco Mira D’Ercole, Auke Rijpma, Conal Smith, and Marcel Timmer. Paris: OECD Publishing. dx.doi.org/10.1787/9789264214262-17-en.

**Comment by morkor** [comment]
I can manually set the citation to the one desired by Auke, but that would mean that the citation information within the xslx files with the data will have a different citation than the one available in dataverse. I can also set manually the three types of citation files (ris, bib, xml) but this would again be violating the conformity of the clio website with dataverse. Auke any ideas?

**Comment by rijpma** [comment]
I'm not too fussed about the citation, so I'd go with something that conforms to the rest of the clio-site
