### ISSUE TITLE
plain text citation

### ISSUE THREAD

**Issue by morkor** [CLARIAH/wp4-requirements#80]
APAlike text citation directly in the xls metadata

**Comment by morkor** [comment]
require(RefManageR)
bib <- ReadBib('/home/michalis/PhD/Clio Infra/Website/Citations/DOI-10622_2EM9DE.bib')
bib <- ReadBib('/home/michalis/PhD/Clio Infra/Website/Citations/DOI-10622_2KHSYM.bib')
bib <- ReadBib('/home/michalis/PhD/Clio Infra/Website/Citations/DOI-10622_4ZDPWP.bib')
TheAuthorAndDate <- capture.output(print(bib, .opts = list(bib.style = "authoryear", first.inits = FALSE, no.print.fields = c("title","publisher","url"))))
xxx <- unlist(bib)
paste(TheAuthorAndDate," ",xxx$title,". ", xxx$url,", accessed via the Clio Infra website.", sep = "")

**Comment by rlzijdeman** [comment]
Hi @morkor, do you think you could define paths in the beginning of your R file and make them relative to your data directory? It will make it easier to transfer your code later on.

**Comment by morkor** [comment]
Hey @rlzijdeman, it is relative already in the actual script, but not in this example[ of the solution].
